//! Root of the `codex-core` library.

// Prevent accidental direct writes to stdout/stderr in library code. All
// user-visible output must go through the appropriate abstraction (e.g.,
// the TUI or the tracing stack).
#![deny(clippy::print_stdout, clippy::print_stderr)]

mod apply_patch;
mod apps;
mod client;
mod client_common;
mod realtime_context;
mod realtime_conversation;
mod realtime_prompt;
mod responses_metadata;
mod responses_retry;
pub(crate) mod session;
pub(crate) use agent::AgentControl;
pub use responses_metadata::CodexResponsesMetadata;
pub use session::SteerInputError;
pub use turn_metadata::detached_memory_responses_metadata;
mod codex_thread;
mod compact_model_fallback;
mod compact_remote;
mod compact_remote_v2;
mod compact_token_budget;
mod config_lock;
#[allow(dead_code)]
mod syndrid_orchestration;
pub use codex_thread::BackgroundTerminalInfo;
pub use codex_thread::CodexThread;
pub use codex_thread::CodexThreadSettingsOverrides;
pub use codex_thread::ThreadConfigSnapshot;
pub use codex_thread::TryStartTurnIfIdleError;
pub use codex_thread::TryStartTurnIfIdleRejectionReason;
pub use session::turn_context::TurnContext;
pub use syndrid_orchestration::BrowserLaunchStatus;
pub use syndrid_orchestration::BuiltInExecutionMode;
pub use syndrid_orchestration::CODEX_PROVIDER_ID;
pub use syndrid_orchestration::CallbackServerError;
pub use syndrid_orchestration::CodexAccountConnectionMetadata;
pub use syndrid_orchestration::CodexAccountProfileError;
pub use syndrid_orchestration::CodexAccountProfileId;
pub use syndrid_orchestration::CodexAccountProfileRegistry;
pub use syndrid_orchestration::CodexAccountProfileState;
pub use syndrid_orchestration::CodexAccountStore;
pub use syndrid_orchestration::CodexCredentialEnvelope;
pub use syndrid_orchestration::CodexCredentialProvider;
pub use syndrid_orchestration::CodexInvocationAdapter;
pub use syndrid_orchestration::CodexInvocationClient;
pub use syndrid_orchestration::ConnectionValidationStatus;
pub use syndrid_orchestration::ExecutionModeSelection;
pub use syndrid_orchestration::ExecutionPolicy;
pub use syndrid_orchestration::ExecutionPolicyError;
pub use syndrid_orchestration::ExecutionShape;
pub use syndrid_orchestration::LiveEvent;
pub use syndrid_orchestration::LiveOrchestrationCoordinator;
pub use syndrid_orchestration::LiveOrchestrationError;
pub use syndrid_orchestration::LiveOrchestrationOutcome;
pub use syndrid_orchestration::LiveOrchestrationRequest;
pub use syndrid_orchestration::LiveOrchestrationTerminal;
pub use syndrid_orchestration::LiveRepairResult;
pub use syndrid_orchestration::LiveRoleOutcome;
pub use syndrid_orchestration::LiveRoleSkipReason;
pub use syndrid_orchestration::LiveRoleState;
pub use syndrid_orchestration::NativeCodexCredentialProvider;
pub use syndrid_orchestration::OMNIROUTE_DEFAULT_BASE_URL;
pub use syndrid_orchestration::OMNIROUTE_PROVIDER_ID;
pub use syndrid_orchestration::ObservationCleanupState;
pub use syndrid_orchestration::ObservationFailureState;
pub use syndrid_orchestration::ObservationQuality;
pub use syndrid_orchestration::ObservationTerminalReason;
pub use syndrid_orchestration::Observed;
pub use syndrid_orchestration::ObservedActiveRole;
pub use syndrid_orchestration::OmniRouteConnectionMetadata;
pub use syndrid_orchestration::OmniRouteConnectionSetupRequest;
pub use syndrid_orchestration::OmniRouteRegistry;
pub use syndrid_orchestration::OpenRouterAuthError;
pub use syndrid_orchestration::OpenRouterConnectionMetadata;
pub use syndrid_orchestration::OpenRouterSetupError;
pub use syndrid_orchestration::OpenRouterSetupRequest;
pub use syndrid_orchestration::OpenRouterSetupStarted;
pub use syndrid_orchestration::OrchestrationObservationReceiver;
pub use syndrid_orchestration::OrchestrationObservationSink;
pub use syndrid_orchestration::OrchestrationObservationSnapshot;
pub use syndrid_orchestration::OrchestrationObservationStage;
pub use syndrid_orchestration::OrchestrationObservationUpdate;
pub use syndrid_orchestration::PlannerTaskSpecification;
pub use syndrid_orchestration::PlanningContract;
pub use syndrid_orchestration::PolicySource;
pub use syndrid_orchestration::ProviderInvocationError;
pub use syndrid_orchestration::ProviderInvocationRequest;
pub use syndrid_orchestration::ProviderInvocationResult;
pub use syndrid_orchestration::ProviderInvocationToolCall;
pub use syndrid_orchestration::ProviderInvocationToolDefinition;
pub use syndrid_orchestration::ProviderInvocationToolResult;
pub use syndrid_orchestration::ProviderInvocationUsage;
pub use syndrid_orchestration::ProviderSelection;
pub use syndrid_orchestration::RepairPolicyDecision;
pub use syndrid_orchestration::ResolvedExecutionPolicy;
pub use syndrid_orchestration::ResolvedExecutionPolicyExplanation;
pub use syndrid_orchestration::RoleActivation;
pub use syndrid_orchestration::RoleExecutionPolicy;
pub use syndrid_orchestration::RoutingAssignment;
pub use syndrid_orchestration::RoutingConnectionDirectory;
pub use syndrid_orchestration::RoutingConnectionInfo;
pub use syndrid_orchestration::RoutingProfile;
pub use syndrid_orchestration::RoutingProfileError;
pub use syndrid_orchestration::RoutingProfileId;
pub use syndrid_orchestration::RoutingProfileRegistry;
pub use syndrid_orchestration::RoutingProfileStore;
pub use syndrid_orchestration::RoutingResolutionStatus;
pub use syndrid_orchestration::RoutingRole;
pub use syndrid_orchestration::ScopedCodexInvocationClient;
pub use syndrid_orchestration::ScopedCodexSession;
pub use syndrid_orchestration::SessionExecutionPolicyState;
pub use syndrid_orchestration::SessionExecutionStateError;
pub use syndrid_orchestration::SessionExecutionStatus;
pub use syndrid_orchestration::SessionPolicySource;
pub use syndrid_orchestration::SessionPolicySummary;
pub use syndrid_orchestration::SessionPolicyValidation;
pub use syndrid_orchestration::SubagentAttemptKind;
pub use syndrid_orchestration::SubagentAttemptOutcome;
pub use syndrid_orchestration::SubagentAttemptState;
pub use syndrid_orchestration::SubagentBatchError;
pub use syndrid_orchestration::SubagentBatchOutcome;
pub use syndrid_orchestration::SubagentBatchRequest;
pub use syndrid_orchestration::SubagentBatchRuntime;
pub use syndrid_orchestration::SubagentBatchStatus;
pub use syndrid_orchestration::SubagentConcurrencyPolicy;
pub use syndrid_orchestration::SubagentDataQuality;
pub use syndrid_orchestration::SubagentError;
pub use syndrid_orchestration::SubagentFailurePolicy;
pub use syndrid_orchestration::SubagentLifecycle;
pub use syndrid_orchestration::SubagentOutcome;
pub use syndrid_orchestration::SubagentProvider;
pub use syndrid_orchestration::SubagentRepairBatchOutcome;
pub use syndrid_orchestration::SubagentRepairBatchRequest;
pub use syndrid_orchestration::SubagentRepairBatchRuntime;
pub use syndrid_orchestration::SubagentRepairBudget;
pub use syndrid_orchestration::SubagentRepairEligibility;
pub use syndrid_orchestration::SubagentRepairError;
pub use syndrid_orchestration::SubagentRepairFailureCategory;
pub use syndrid_orchestration::SubagentRepairOutcome;
pub use syndrid_orchestration::SubagentRepairPolicy;
pub use syndrid_orchestration::SubagentRepairRoute;
pub use syndrid_orchestration::SubagentRepairRuntime;
pub use syndrid_orchestration::SubagentRepairTerminal;
pub use syndrid_orchestration::SubagentRequest;
pub use syndrid_orchestration::SubagentResultOrdering;
pub use syndrid_orchestration::SubagentRuntime;
pub use syndrid_orchestration::SubagentSessionBudget;
pub use syndrid_orchestration::SubagentStatus;
pub use syndrid_orchestration::SubagentTask;
pub use syndrid_orchestration::SubagentTaskOutcome;
pub use syndrid_orchestration::SubagentTaskState;
pub use syndrid_orchestration::SubagentToolCallRecord;
pub use syndrid_orchestration::SubagentToolError;
pub use syndrid_orchestration::SubagentToolKind;
pub use syndrid_orchestration::SubagentToolPolicy;
pub use syndrid_orchestration::SubagentUsage;
pub use syndrid_orchestration::UnavailableCodexInvocationClient;
pub use syndrid_orchestration::VerificationContract;
pub use syndrid_orchestration::VerificationDecision;
pub use syndrid_orchestration::WatchOrchestrationObservationSink;
pub use syndrid_orchestration::codex_auth_exists;
pub use syndrid_orchestration::delete_codex_auth;
pub use syndrid_orchestration::delete_omniroute_credential;
pub use syndrid_orchestration::invoke_codex;
pub use syndrid_orchestration::invoke_omniroute;
pub use syndrid_orchestration::list_omniroute_models;
pub use syndrid_orchestration::observation_channel;
pub use syndrid_orchestration::omniroute_credential_exists;
pub use syndrid_orchestration::provider_credential_exists;
pub use syndrid_orchestration::retrieve_codex_envelope;
pub use syndrid_orchestration::setup_omniroute;
pub use syndrid_orchestration::setup_openrouter;
pub use syndrid_orchestration::store_codex_auth;
pub use tokio_util::sync::CancellationToken as OpenRouterSetupCancellation;
mod agent;
mod agent_communication;
mod attestation;
mod codex_delegate;
mod command_canonicalization;
pub mod config;
pub mod connectors;
pub mod context;
mod context_manager;
mod current_time;
mod elicitation;
mod environment_selection;
pub mod exec;
pub mod exec_env;
mod exec_policy;
#[cfg(test)]
mod git_info_tests;
mod guardian;
mod hook_runtime;
mod image_preparation;
mod installation_id;
pub(crate) mod landlock;
pub use landlock::spawn_command_under_linux_sandbox;
pub(crate) mod mcp;
mod mcp_skill_dependencies;
mod mcp_tool_approval_templates;
mod mcp_tool_exposure;
mod network_policy_decision;
pub(crate) mod network_proxy_loader;
pub use mcp::McpManager;
pub use network_proxy_loader::MtimeConfigReloader;
pub use network_proxy_loader::build_network_proxy_state;
pub use network_proxy_loader::build_network_proxy_state_and_reloader;
mod original_image_detail;
pub use codex_mcp::CodexAppsToolsCache;
pub use codex_mcp::SandboxState;
mod mcp_openai_file;
mod mcp_tool_call;
pub(crate) mod mention_syntax;
pub(crate) mod utils;
pub use mention_syntax::PLUGIN_TEXT_MENTION_SIGIL;
pub use mention_syntax::TOOL_MENTION_SIGIL;
pub use utils::path_utils;
pub(crate) mod plugins;
#[doc(hidden)]
pub(crate) mod prompt_debug;
#[doc(hidden)]
pub use prompt_debug::build_prompt_input;
pub(crate) mod mentions {
    pub(crate) use crate::plugins::build_connector_slug_counts;
    pub(crate) use crate::plugins::build_skill_name_counts;
    pub(crate) use crate::plugins::collect_explicit_app_ids;
    pub(crate) use crate::plugins::collect_explicit_plugin_mentions;
    pub(crate) use crate::plugins::collect_tool_mentions_from_messages;
}
mod sandbox_tags;
pub mod sandboxing;
mod session_prefix;
mod session_startup_prewarm;
pub mod skills;
pub(crate) use skills::SkillInjections;
pub(crate) use skills::SkillMetadata;
pub(crate) use skills::SkillsService;
pub(crate) use skills::build_available_skills;
pub(crate) use skills::build_skill_injections;
pub(crate) use skills::build_skill_name_counts;
pub(crate) use skills::collect_explicit_skill_mentions;
pub(crate) use skills::default_skill_metadata_budget;
pub(crate) use skills::injection;
pub(crate) use skills::maybe_emit_implicit_skill_invocation;
pub(crate) use skills::skills_load_input_from_config;
mod stream_events_utils;
pub use stream_events_utils::image_generation_artifact_path;
pub mod test_support;
mod unified_exec;
pub mod windows_sandbox;
pub use client::X_RESPONSESAPI_INCLUDE_TIMING_METRICS_HEADER;
pub use codex_protocol::config_types::ModelProviderAuthInfo;
mod event_mapping;
pub use codex_prompts as review_prompts;
mod thread_manager;
pub(crate) mod web_search;
pub(crate) mod windows_sandbox_read_grants;
pub use thread_manager::ForkSnapshot;
pub use thread_manager::NewThread;
pub use thread_manager::StartThreadOptions;
pub use thread_manager::ThreadManager;
pub use thread_manager::ThreadShutdownReport;
pub use thread_manager::build_models_manager;
pub use thread_manager::local_agent_graph_store_from_state_db;
pub use thread_manager::thread_store_from_config;
pub use web_search::web_search_action_detail;
pub use web_search::web_search_detail;
pub use windows_sandbox_read_grants::grant_read_root_non_elevated;
#[deprecated(note = "use ThreadManager")]
pub type ConversationManager = ThreadManager;
#[deprecated(note = "use NewThread")]
pub type NewConversation = NewThread;
#[deprecated(note = "use CodexThread")]
pub type CodexConversation = CodexThread;
pub(crate) mod agents_md;
mod agents_md_manager;
pub use agents_md::DEFAULT_AGENTS_MD_FILENAME;
pub use agents_md::LOCAL_AGENTS_MD_FILENAME;
pub use agents_md::LoadedAgentsMd;
mod rollout;
mod rollout_budget;
pub(crate) mod safety;
mod session_rollout_init_error;
pub mod shell;
pub(crate) mod shell_snapshot;
pub mod spawn;
pub(crate) mod state_db_bridge;
pub use state_db_bridge::StateDbHandle;
pub use state_db_bridge::init_state_db;
mod thread_rollout_truncation;
pub use thread_rollout_truncation::truncate_rollout_after_turn_id;
mod tools;
pub(crate) mod turn_diff_tracker;
mod turn_metadata;
mod turn_timing;
pub use rollout::ARCHIVED_SESSIONS_SUBDIR;
pub use rollout::Cursor;
pub use rollout::INTERACTIVE_SESSION_SOURCES;
pub use rollout::RolloutRecorder;
pub use rollout::RolloutRecorderParams;
pub use rollout::SESSIONS_SUBDIR;
pub use rollout::SessionMeta;
pub use rollout::SortDirection;
pub use rollout::ThreadItem;
pub use rollout::ThreadSortKey;
pub use rollout::ThreadsPage;
pub use rollout::append_thread_name;
pub use rollout::find_archived_thread_path_by_id_str;
#[deprecated(note = "use find_thread_path_by_id_str")]
pub use rollout::find_conversation_path_by_id_str;
pub use rollout::find_thread_meta_by_name_str;
pub use rollout::find_thread_name_by_id;
pub use rollout::find_thread_names_by_ids;
pub use rollout::find_thread_path_by_id_str;
pub use rollout::parse_cursor;
pub use rollout::read_head_for_summary;
pub use rollout::read_session_meta_line;
pub use rollout::rollout_date_parts;
mod function_tool;
mod state;
mod tasks;
mod user_shell_command;
pub mod util;

pub use attestation::AttestationContext;
pub use attestation::AttestationProvider;
pub use attestation::GenerateAttestationFuture;
pub use client::ModelClient;
pub use client::ModelClientSession;
pub use client::X_CODEX_INSTALLATION_ID_HEADER;
pub use client::X_CODEX_TURN_METADATA_HEADER;
pub use client_common::Prompt;
pub use client_common::ResponseEvent;
pub use client_common::ResponseStream;
pub use codex_prompts::REVIEW_PROMPT;
pub use compact::content_items_to_text;
pub use current_time::SleepFuture;
pub use current_time::TimeFuture;
pub use current_time::TimeProvider;
pub use event_mapping::parse_turn_item;
pub use exec_policy::ExecPolicyError;
pub use exec_policy::check_execpolicy_for_warnings;
pub use exec_policy::format_exec_policy_error_with_source;
pub use exec_policy::load_exec_policy;
pub use installation_id::resolve_installation_id;
pub mod compact;
mod memory_usage;
pub mod otel_init;
