// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { GitStatusEntry } from "./GitStatusEntry";

/**
 * Bounded repository status returned by `git/status`.
 */
export type GitStatusResponse = {
entries: Array<GitStatusEntry>,
/**
 * True when more entries existed than the runtime response retained.
 */
truncated: boolean, };
