// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { GitStatusCode } from "./GitStatusCode";

/**
 * Typed file status reported by the Syndrid runtime.
 */
export type GitStatusEntry = {
/**
 * Current path in the worktree.
 */
path: string,
/**
 * Original path when Git reports a rename or copy.
 */
previousPath: string | null,
/**
 * Index/staging-area state.
 */
indexStatus: GitStatusCode,
/**
 * Working-tree state.
 */
worktreeStatus: GitStatusCode, };
