// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read the selected repository's index and working-tree status.
 */
export type GitStatusParams = {
/**
 * Absolute working directory inside the repository to inspect.
 */
cwd: string, };
