// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single side of a porcelain-v1 Git status record.
 */
export type GitStatusCode = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "unmerged" | "untracked" | "ignored";
