// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read the repository's linked-worktree inventory.
 */
export type GitWorktreeListParams = {
/**
 * Absolute working directory inside the repository to inspect.
 */
cwd: string,
/**
 * Maximum number of worktree entries to retain. The runtime applies its
 * bounded default and maximum when omitted or set above the supported cap.
 */
limit?: number | null, };
