// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { GitWorktreeEntry } from "./GitWorktreeEntry";

/**
 * Bounded linked-worktree inventory returned by `git/worktree/list`.
 */
export type GitWorktreeListResponse = {
entries: Array<GitWorktreeEntry>,
/**
 * True when more entries existed than the runtime response retained.
 */
truncated: boolean, };
