// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A linked Git worktree reported by the Syndrid runtime.
 */
export type GitWorktreeEntry = {
/**
 * Native absolute worktree path as reported by Git.
 */
path: string,
head: string | null,
/**
 * Local branch name without the `refs/heads/` prefix when attached.
 */
branch: string | null,
detached: boolean,
bare: boolean,
locked: boolean,
lockReason: string | null,
prunable: boolean,
pruneReason: string | null,
/**
 * True for the worktree containing the request cwd.
 */
current: boolean, };
