// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Change kind for one file in the remote-relative Git diff.
 */
export type GitDiffChangeKind = "modified" | "added" | "deleted" | "renamed";
