// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitDiffChangeKind } from "./GitDiffChangeKind";

/**
 * Runtime-owned metadata for one file in the remote-relative Git diff.
 */
export type GitDiffChange = { path: string, previousPath: string | null, kind: GitDiffChangeKind, addedLines: number, removedLines: number, };
